title: Edinburgh Coop Meetup
url: https://edinburgh-coop-meetup.github.io
baseurl:

collections:
  event:
    output: true
    sort_by: start
  link:
    sort_by: title

exclude:
  - LICENSE.txt
  - README.md
  - datatig.yaml
keep_files:
  - datatig
