# TOUSE: Replace with the title of your group
title: Event Website Template
# TOUSE: Replace url and baseurl with your site address
url: https://jarofgreen.github.io
baseurl: /event-website-template

collections:
  event:
    output: true
    sort_by: start
  link:
    sort_by: title

exclude:
  - LICENSE.txt
  - README.md
  - datatig.yaml
keep_files:
  - datatig
