title: Event Website Template
url: https://jarofgreen.github.io
baseurl: /event-website-template

collections:
  event:
    output: true
    sort_by: start
  link:
    sort_by: title

exclude:
  - LICENSE.txt
  - README.md
