name: Build and Deploy
on: [push, pull_request]

jobs:
  build_deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Make output directory
      run: "mkdir _site"
    - name: Build site
      run: "docker run --rm --volume=\"${{ github.workspace }}:/srv/jekyll:Z\" jekyll/builder:4 /bin/bash -c 'chmod 777 /srv/jekyll && jekyll build _site'"
    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: "./_site"
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
