name: Build and Deploy
on: [push, pull_request]

jobs:
  build_deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
        architecture: x64
    - name: Make output directory
      run: "mkdir -p _site/datatig"
    - name: Install DataTig
      run: "pip install datatig"
    - name: Build DataTig site
      # TOUSE: Replace the URL with the URL of your site, but leave /datatig at the end
      run: "python -m datatig.cli build . --staticsiteoutput _site/datatig --staticsiteurl https://jarofgreen.github.io/event-website-template/datatig"
    - name: Build Jekyll site
      run: "docker run --rm --volume=\"${{ github.workspace }}:/srv/jekyll:Z\" jekyll/builder:4 /bin/bash -c 'chmod 777 /srv/jekyll && jekyll build _site'"
    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: "./_site"
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
